# Generated by Django 3.0.2 on 2020-04-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=25, verbose_name='city')),
                ('CONFIRMED', models.IntegerField(max_length=7)),
                ('ACTIVE', models.IntegerField(max_length=7)),
                ('RECOVERED', models.IntegerField(max_length=7)),
                ('DECEASED', models.IntegerField(max_length=7)),
            ],
        ),
    ]
