# Generated by Django 3.0.2 on 2020-04-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidrecord',
            name='ACTIVE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='covidrecord',
            name='CONFIRMED',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='covidrecord',
            name='DECEASED',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='covidrecord',
            name='RECOVERED',
            field=models.IntegerField(),
        ),
    ]
