# Generated by Django 3.0.2 on 2020-04-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20200403_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CovidRecord',
        ),
    ]
